ExpertSolution/Controllers/ApplicationFormController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using System.Text.Json;
using static Dapper.SqlMapper;

namespace ExpertSolution.Controllers
{
    public class ApplicationFormController : BaseController
    {
        private readonly IApplicationFormDAO _ApplicationFormDAO;
        private readonly IMailService _mailService;
        private readonly ConfigConstants _configConstants;
        private readonly IFormsDAO _FormsDAO;
        private readonly ICommonDAO _CommonDAO;

        public ApplicationFormController(IApplicationFormDAO applicationFormDAO, IFormsDAO formsDAO, ICommonDAO commonDAO,IMailService mailService, IOptions<ConfigConstants> configConstants)
        {
            _ApplicationFormDAO = applicationFormDAO;
            _mailService = mailService;
            _configConstants = configConstants.Value;
            _FormsDAO = formsDAO;
            _CommonDAO = commonDAO;

        }
        public IActionResult Index(string id = "", string evaluator = "",string action="")
        {
            UserMainInformation obj = UserInfo;
            if (obj == null || obj.Id <= 0)
            {
                return new RedirectResult("~/account/Login");
            }
            ViewBag.Id = id;
            ViewBag.Evaluator = evaluator;
            if (!string.IsNullOrEmpty(id) && obj.UserType == 1)
            {
                return new RedirectResult("~/account/Login");
            }
            //if (string.IsNullOrEmpty(obj.WorkOn) && action.ToLower() != "index")
            //{
            //    return View("About");
            //}
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public ActionResult SaveMainInformation(UserMainInformation UserMainInformation)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                int id = _ApplicationFormDAO.SaveMainInformation(UserMainInformation);
                if (id > 0)
                {
                    dic.Add("Valid", true);
                }
                else
                {
                    dic.Add("Valid", false);
                }

            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        #region QuastionsYesOrNo
        [HttpGet]
        public ActionResult GetExpertQuestionAnswers(string expertGUID)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                if (string.IsNullOrEmpty(expertGUID))
                {
                    dic.Add("Valid", false);
                    dic.Add("Message", "ExpertGUID is required.");
                    return Json(Utility.GetExtendedJsonResult(dic));
                }

                List<ExpertQuestionAnswer> answers = _FormsDAO.getExpertQuestionAnswers(expertGUID);

                if (answers.Count > 0)
                {
                    dic.Add("Valid", true);
                    dic.Add("result", answers);
                }
                else
                {
                    dic.Add("Valid", false);
                }
            }
            catch (Exception ex)
            {
                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }

            return Json(Utility.GetExtendedJsonResult(dic));
        }


        [HttpPost]
        public ActionResult SaveExpertQuestionAnswers([FromBody] List<ExpertQuestionAnswer> Answers)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                int id = _FormsDAO.SaveExpertQuestionAnswers(Answers);
                if (id > 0)
                {
                    dic.Add("Valid", true);
                    dic.Add("id", id);
                }
                else
                {
                    dic.Add("Valid", false);
                }
            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        #endregion

        #region Professionalqualifications
        public ActionResult SaveProfessionalqualifications(ProfessionalQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                int id = _FormsDAO.SaveProfessionalQualifications(entity);
                if (id > 0)
                {
                    dic.Add("Valid", true);
                    dic.Add("id", id);
                }
                else
                {
                    dic.Add("Valid", false);
                }

            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult GetALLProfessionalQualifications(ProfessionalQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                List<ProfessionalQualifications> lst = _FormsDAO.GetALLProfessionalQualifications(entity.UserGUID);

                if (lst.Count > 0)
                {
                    dic.Add("Valid", true);
                    dic.Add("result", lst);
                }
                else
                {
                    dic.Add("Valid", false);
                }

            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult GetProfessionalqualificationsById(ProfessionalQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                ProfessionalQualifications obj = _FormsDAO.GetByIdProfessionalQualifications(entity.Id);
                dic.Add("Valid", true);
                dic.Add("result", obj);


            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult DeleteProfessionalqualifications(ProfessionalQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                int x = _FormsDAO.DeleteProfessionalQualifications(entity.Id);
                dic.Add("Valid", true);


            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        #endregion

        #region AcademicQualifications
        public ActionResult SaveAcademicQualifications(AcademicQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                int id = _FormsDAO.SaveAcademicQualifications(entity);
                if (id > 0)
                {
                    dic.Add("Valid", true);
                    dic.Add("id", id);
                }
                else
                {
                    dic.Add("Valid", false);
                }

            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult GetALLAcademicQualifications(AcademicQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                List<AcademicQualifications> lst = _FormsDAO.GetALLAcademicQualifications(entity.UserGUID);

                if (lst.Count > 0)
                {
                    dic.Add("Valid", true);
                    dic.Add("result", lst);
                }
                else
                {
                    dic.Add("Valid", false);
                }

            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult GetAcademicQualificationsById(AcademicQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                AcademicQualifications obj = _FormsDAO.GetByIdAcademicQualifications(entity.Id);
                dic.Add("Valid", true);
                dic.Add("result", obj);


            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult DeleteAcademicQualifications(AcademicQualifications entity)
        {
            var dic = new Dictionary<string, object>();

            try
            {
                int x = _FormsDAO.DeleteAcademicQualifications(entity.Id);
                dic.Add("Valid", true);


            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }
            return Json(Utility.GetExtendedJsonResult(dic));


        }
        #endregion

        #region CertificateQualifications

ExpertSolution/Controllers/ApplicationFormManageController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Net.Mail;
using System.Resources;

namespace ExpertSolution.Controllers
{
    public class ApplicationFormManageController : BaseController
    {
        private readonly IApplicationFormDAO _ApplicationFormDAO;
        private readonly IEvaluationDAO _evaluationDAO;

        public ApplicationFormManageController(IApplicationFormDAO applicationFormDAO, IEvaluationDAO evaluationDAO)
        {
            _ApplicationFormDAO = applicationFormDAO;
            _evaluationDAO = evaluationDAO;
        }
        

        public IActionResult Index(ApplicationFormFilter model)
        {
            UserMainInformation obj = UserInfo;
            if (obj == null || obj.Id <= 0)
            {
                return new RedirectResult("~/account/Login");
            }
            List <ApplicationFormUI> lst = _ApplicationFormDAO.GetAllApplicationForms(model);
            return View(lst);
        }
        public IActionResult EvaluationResult(int evaluatorGroupId)
        {
            UserMainInformation obj = UserInfo;
            if (obj == null || obj.Id <= 0)
            {
                return new RedirectResult("~/account/Login");
            }
            List<ApplicationFormUI> lst = _evaluationDAO.GetByEvaluationGroup(evaluatorGroupId);
            return View(lst);
        }
        public IActionResult CountryLst()
        {
            UserMainInformation obj = UserInfo;
            if (obj == null || obj.Id <= 0)
            {
                return new RedirectResult("~/account/Login");
            }
            List<ApplicationFormCount> lst = _ApplicationFormDAO.GetApplicationFormCountbyCountry();
            return View(lst);
        }
        public IActionResult DashBoard()
        {
            UserMainInformation obj = UserInfo;
            if (obj == null || obj.Id <= 0)
            {
                return new RedirectResult("~/account/Login");
            }
            return View();
        }
        

    }
}

ExpertSolution/Views/Shared/_Header.cshtml
@{
    var userInfo = Html.GetUserinfo();
}
<div class="navbar-header droid-arabic-kufi">
    <div class="row align-items-center justify-content-between">
        <div class="col-auto">
            <div class="d-flex flex-wrap align-items-center gap-4">
                <button type="button" class="sidebar-toggle" id="kt_aside_toggle">
                    <iconify-icon icon="heroicons:bars-3-solid" class="icon text-2xl active"></iconify-icon>
                    <iconify-icon icon="iconoir:arrow-right" class="icon text-2xl  non-active"></iconify-icon>
                </button>
                <button type="button" class="sidebar-mobile-toggle">
                    <iconify-icon icon="heroicons:bars-3-solid" class="icon"></iconify-icon>
                </button>
               
            </div>
        </div>
        <div class="col-auto">
            <div class="d-flex flex-wrap align-items-center gap-3">
                <button type="button" data-theme-toggle class="w-32-px h-32-px bg-neutral-200 rounded-circle d-flex justify-content-center align-items-center"></button>
                <!-- Messages Dropdown -->
                <div class="dropdown">
                    <button class="btn btn-icon btn-light  bg-neutral-200 rounded-circle position-relative" type="button" data-bs-toggle="dropdown">
                        <iconify-icon icon="mage:email" class="text-primary-light text-xl"></iconify-icon>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-circle bg-danger">3</span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end p-0">
                        <div class="dropdown-header  py-3 px-4">
                            <h6 class="mb-0 d-flex justify-content-center align-items-center form-label">الرسائل</h6>
                        </div>
                        <div class="dropdown-body p-2" style="min-width: 250px;">
                            <!-- Message items would go here -->
                        </div>
                    </div>
                </div>

                <!-- Notifications Dropdown -->
                <div class="dropdown">
                    <button class="btn btn-icon btn-light  bg-neutral-200 rounded-circle position-relative" type="button" data-bs-toggle="dropdown">
                        <iconify-icon icon="iconoir:bell" class="text-primary-light text-xl"></iconify-icon>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-circle bg-danger">5</span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end p-0">
                        <div class="dropdown-header  py-3 px-4">
                            <h6 class="mb-0 d-flex justify-content-center align-items-center form-label">الإشعارات</h6>
                        </div>
                        <div class="dropdown-body p-2" style="min-width: 250px;">
                            <div class="d-flex justify-content-center align-items-center" style="min-height: 200px;">

                                <div class="toast-container justify-content-between">
                                    <div class="toast d-block" role="alert"  aria-live="assertive" aria-atomic="true">
                                        <div class="toast-header">
                                            <iconify-icon icon="iconoir:bell" class="text-primary-light text-xl"></iconify-icon>
                                            <strong class="me-auto">الرسالة الاولي</strong>
                                            <small class="text-muted">الان</small>
                                            @* <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button> *@
                                        </div>
                                        <div class="toast-body">
انظر....................                                        </div>
                                    </div>

                                    <div class="toast d-block" role="alert" aria-live="assertive" aria-atomic="true">
                                        <div class="toast-header">
                                            <iconify-icon icon="iconoir:bell" class="text-primary-light text-xl"></iconify-icon>
                                            <strong class="me-auto">الرساله الثانية</strong>
                                            <small class="text-muted">  ثانيتان</small>
                                            @* <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button> *@
                                        </div>
                                        <div class="toast-body">
تم اشتراك احمد                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>


                <!-- Notification dropdown end -->

                @* <div class="dropdown"> *@
                @*     <button class="d-flex justify-content-center align-items-center rounded-circle" type="button" data-bs-toggle="dropdown"> *@
                @*         <img src="~/assets/images/user.png" alt="image" class="w-32-px h-32-px object-fit-cover rounded-circle"> *@
                @*     </button> *@
                @*     <div class="dropdown-menu to-top dropdown-menu-sm"> *@
                @*         <div class="py-12 px-16 radius-8 bg-primary-50 mb-16 d-flex align-items-center justify-content-between gap-2"> *@
                @*             <div> *@
                @*                 <h6 class="text-lg text-primary-light fw-semibold mb-2">@userInfo.ContactFullName</h6> *@
                @*                 <span class="text-secondary-light fw-medium text-sm">@userInfo.Email</span> *@
                @*             </div> *@
                @*             <button type="button" class="hover-text-danger"> *@
                @*                 <iconify-icon icon="radix-icons:cross-1" class="icon text-xl"></iconify-icon> *@
                @*             </button> *@
                @*         </div> *@
                @*         <ul class="to-top-list"> *@
                        
                @*             <li> *@
                @*                 <a class="dropdown-item text-black px-0 py-8 hover-bg-transparent hover-text-primary d-flex align-items-center gap-3" href=" @Url.Action("ChangePassword", "Account")"> *@
                @*                     <iconify-icon icon="icon-park-outline:setting-two" class="icon text-xl"></iconify-icon>  تحديث كلمة المرور *@
                @*                 </a> *@
                @*             </li> *@
                @*             <li> *@
                @*                 <a class="dropdown-item text-black px-0 py-8 hover-bg-transparent hover-text-danger d-flex align-items-center gap-3" href="@Url.Action("Login", "Account")"> *@
                @*                     <iconify-icon icon="lucide:power" class="icon text-xl"></iconify-icon>  خروج *@
                @*                 </a> *@
                @*             </li> *@
                @*         </ul> *@
                @*     </div> *@
                @* </div> *@
                
                <!-- Profile dropdown end -->
            </div>
        </div>
    </div>
</div>
<style>
 
    
    .btn-icon {
        width: 40px;
        height: 40px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        padding: 0;
    }
    
    .dropdown-menu {
        border-radius: 8px;
        border: none;
        box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.1);
    }
    
    .dropdown-item {
        border-radius: 6px;
        margin: 0 4px;
        transition: all 0.2s;
    }
    
    .dropdown-item:hover {
        background-color: #f8f9fa;
    }
    
    .dropdown-header {
        background-color: #f8f9fa;
        border-radius: 8px 8px 0 0;
    }
    
    .w-40-px {
        width: 40px;
    }
    
    .h-40-px {
        height: 40px;
    }
</style>

ExpertSolution/Views/Shared/_Layout.cshtml
<!-- meta tags and other links -->
<!DOCTYPE html>
<html lang="ar" dir="rtl" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>مبادرة اعتماد الخبراء في مجال التواصل والعلاقات العامة</title>
    <link rel="icon" type="image/png" href="~/assets/images/logo-icon.png" sizes="16x16">
    <!-- remix icon font css  -->
    <link rel="stylesheet" href="~/assets/css/remixicon.css">
    <!-- BootStrap css -->
    <link rel="stylesheet" href="~/assets/css/lib/bootstrap.min.css">
    <!-- Apex Chart css -->
    <link rel="stylesheet" href="~/assets/css/lib/apexcharts.css">
    <!-- Data Table css -->
@*     <link rel="stylesheet" href="~/assets/css/lib/dataTables.min.css">
 *@    <!-- Text Editor css -->
    <link rel="stylesheet" href="~/assets/css/lib/editor-katex.min.css">
    <link rel="stylesheet" href="~/assets/css/lib/editor.atom-one-dark.min.css">
    <link rel="stylesheet" href="~/assets/css/lib/editor.quill.snow.css">
    <!-- Date picker css -->
    <link rel="stylesheet" href="~/assets/css/lib/flatpickr.min.css">
    <!-- Calendar css -->
    <link rel="stylesheet" href="~/assets/css/lib/full-calendar.css">
    <!-- Vector Map css -->
    <link rel="stylesheet" href="~/assets/css/lib/jquery-jvectormap-2.0.5.css">
    <!-- Popup css -->
    <link rel="stylesheet" href="~/assets/css/lib/magnific-popup.css">
    <!-- Slick Slider css -->
    <link rel="stylesheet" href="~/assets/css/lib/slick.css">

    <!-- main css -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/css/Expert.css">
    <link rel="stylesheet" href="~/css/ExpertInner.css">
    <link href="~/assets/css/sweetalert.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Phone/css/intlTelInput.css" />
    <link rel="stylesheet" href="~/Phone/css/demo.css" />
    @RenderSection("Styles", required: false)
    <script src="~/assets/js/lib/jquery-3.7.1.min.js"></script>
    <!-- Bootstrap js -->
    <script src="~/assets/js/lib/bootstrap.bundle.min.js"></script>
    <!-- Apex Chart js -->
    
    <!-- Data Table js -->
@*     <script src="~/assets/js/lib/dataTables.min.js"></script>
 *@    <!-- Iconify Font js -->
    <script src="~/assets/js/lib/iconify-icon.min.js"></script>
    <!-- jQuery UI js -->
    <script src="~/assets/js/lib/jquery-ui.min.js"></script>
    <!-- Vector Map js -->
    <script src="~/assets/js/lib/jquery-jvectormap-2.0.5.min.js"></script>
    <script src="~/assets/js/lib/jquery-jvectormap-world-mill-en.js"></script>
    <!-- Popup js -->
    <script src="~/assets/js/lib/magnifc-popup.min.js"></script>
    <!-- Slick Slider js -->
    <script src="~/assets/js/lib/slick.min.js"></script>
    <script src="~/assets/js/sweetalert.min.js"></script>
    <!-- main js -->
  
    <script src="~/js/Expert.Init.js"></script>
    <script src="~/js/Expert.js"></script>
    <!-- Old SweetAlert -->
 
    <script>
        // let table = new DataTable('#dataTable');
    </script>
</head>
<body class="bg-base">
    @{
        var userInfo = Html.GetUserinfo();
    }
    <aside class="sidebar">
        <button type="button" class="sidebar-close-btn">
            <iconify-icon icon="radix-icons:cross-2"></iconify-icon>
        </button>
        <div>
            <a href="index.html" class="sidebar-logo">
                <img src="~/assets/images/logo.png" alt="site logo" class="light-logo">
                <img src="~/assets/images/logo.png" alt="site logo" class="dark-logo">
                <img src="~/assets/images/logo-icon.png" alt="site logo" class="logo-icon">
            </a>
        </div>
        <div class="sidebar-menu-area">
              @if (userInfo.UserType == 2)
            {
            @await Html.PartialAsync("_MenuAdmin")
            }
            else if (userInfo.UserType == 1)
            { 
            @await Html.PartialAsync("_Menu")
             }
            else if (userInfo.UserType == 3)
            {
            @await Html.PartialAsync("_MenuEvaluator")
            }
        </div>
    </aside>

    <main class="dashboard-main">
        @await Html.PartialAsync("_Header")

        <div class="dashboard-main-body">

            @RenderBody()
        </div>

        <footer class="d-footer">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto">
                    <p class="mb-0">©   جميع الحقوق محفوظة.</p>
                </div>
                <div class="col-auto">
                    <p class="mb-0"> مبادرة اعتماد الخبراء  في مجال التواصل والعلاقات العامة</p>
                </div>
            </div>
        </footer>
    </main>
    <script src="~/assets/js/app.js"></script>
    <!-- jQuery library js -->
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        (() => {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            const forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.from(forms).forEach(form => {
                form.addEventListener('submit', event => {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
        })()
    </script>
    <script>
        // swal('خطأ', 'يرجى التأكد من اسم المستخدم وكلمة المرور', 'error');
        // ================== Password Show Hide Js Start ==========
        function initializePasswordToggle(toggleSelector) {
            $(toggleSelector).on('click', function () {
                $(this).toggleClass("ri-eye-off-line");
                var input = $($(this).attr("data-toggle"));
                if (input.attr("type") === "password") {
                    input.attr("type", "text");
                } else {
                    input.attr("type", "password");
                }
            });
        }
        // Call the function
        initializePasswordToggle('.toggle-password');
        // ========================= Password Show Hide Js End ===========================
    </script>
    <script>
        $(document).ready(function () {
            // $('#kt_aside_toggle').trigger("click");
            //jQuery(window).load(function () {
            // $("body").addClass("toggle-sidebar");
            // });
            if ($(window).width() > 1200)
                $('#kt_aside_toggle').trigger("click");
        });
    </script>
   
</body>
</html>

ExpertSolution/Views/Shared/_Menu.cshtml
@{
    var userInfo = Html.GetUserinfo();
}
<ul class="sidebar-menu" id="sidebar-menu">
   @*  <li class="dropdown">
        <a href="javascript:void(0)">
            <iconify-icon icon="solar:home-smile-angle-outline" class="menu-icon"></iconify-icon>
            <span>القائمة الرئيسية</span>
        </a>
        <ul class="sidebar-submenu">
            <li>
                <a href="@Url.Action("Index", "ApplicationForm")"><i class="ri-circle-fill circle-icon text-primary-600 w-auto"></i> التسجيل</a>
            </li>
           
        </ul>
    </li> *@
    <li>
        <a href="@Url.Action("About", "ApplicationForm")">
            <iconify-icon icon="solar:document-text-outline" class="menu-icon"></iconify-icon>
            <span>عن المبادرة</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "ApplicationForm")">
            <iconify-icon icon="heroicons:document" class="menu-icon"></iconify-icon>
            <span>التسجيل</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Login", "Account")">
            <iconify-icon icon="lucide:power" class="menu-icon"></iconify-icon>
            <span>خروج</span>
        </a>
    </li>


    <!-- User Profile Dropdown -->
    <li class="menu-item user-profile  mt-auto">
        <a class="menu-link  text-decoration-none d-flex align-items-center" href="#" role="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="~/assets/images/user.png" alt="User" class="menu-icon " >
            <span class="menu-text me-auto">@userInfo.ContactFullName</span>
            

        </a>
        <ul class="dropdown-menu dropdown-menu-end w-100" aria-labelledby="userDropdown">

            <li>
                <a class="dropdown-item text-black px-3 py-2 d-flex align-items-center gap-3 hover-bg-transparent hover-text-primary" href="@Url.Action("ChangePassword", "Account")">
                    <iconify-icon icon="icon-park-outline:setting-two" class="fs-5"></iconify-icon>
                    <span>تحديث كلمة المرور</span>
                </a>
            </li>
            <li><hr class="dropdown-divider my-1"></li>
            <li>
                <a class="dropdown-item text-black px-3 py-2 d-flex align-items-center gap-3 hover-bg-transparent hover-text-danger" href="@Url.Action("Login", "Account")">
                    <iconify-icon icon="lucide:power" class="fs-5"></iconify-icon>
                    <span>خروج</span>
                </a>
            </li>
        </ul>
    </li>


   
</ul>

ExpertSolution/Views/Shared/_MenuAdmin.cshtml
@inject ICommonDAO _CommonDAO;

@{
    var EvaluatorGroupLst = _CommonDAO.GetEvaluatorGroup();
    }
    <ul class="sidebar-menu" id="sidebar-menu">
    <li>
        <a href="@Url.Action("Dashboard", "ApplicationFormManage")">
            <iconify-icon icon="solar:home-smile-angle-outline" class="menu-icon"></iconify-icon>
            <span>الصفحة الرئيسية</span>
        </a>
    </li>
    <li>
        <a href="/ApplicationFormManage">
            <iconify-icon icon="solar:document-text-outline" class="menu-icon"></iconify-icon>
            <span>قائمة الخبراء</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Login", "Account")">
            <iconify-icon icon="lucide:power" class="menu-icon"></iconify-icon>
            <span>خروج</span>
        </a>
    </li>
   
</ul>