ExpertSolution/Controllers/EvaluationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Web;
using Newtonsoft.Json;
using Shared.Model;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Http.Extensions;
using System.Reflection;
using DAO.Interfaces;
using DAO;

namespace ExpertSolution.Controllers
{
    public class EvaluationController : BaseController
    {
        private readonly IUserMainInformationDAO _UserDAO;
        private readonly IMailService _mailService;
        private readonly IApplicationFormDAO _ApplicationFormDAO;
        private readonly IEvaluationDAO _evaluationDAO;
        public EvaluationController(IUserMainInformationDAO userDAO, IMailService mailService, IEvaluationDAO evaluationDAO, IApplicationFormDAO applicationFormDAO)
        {
            _UserDAO = userDAO;
            _mailService = mailService;
            _evaluationDAO = evaluationDAO;
            _ApplicationFormDAO = applicationFormDAO;
        }

        public ActionResult AccountSave(UserMainInformation UserMainInformation)
        {
            var dic = new Dictionary<string, object>();
            int id = 0;
            if (string.IsNullOrEmpty(UserMainInformation.GUID))
            {
                UserMainInformation userobj = _UserDAO.GetByEmail(UserMainInformation.Email);
                if (userobj.Id > 0)
                {
                    dic.Add("Valid", false);
                    return Json(Utility.GetExtendedJsonResult(dic));
                }
            }

            try
            {
                if (string.IsNullOrEmpty(UserMainInformation.GUID))
                {
                    UserMainInformation.GUID = Guid.NewGuid().ToString();
                    UserMainInformation.UserType = 3;
                    id = _UserDAO.SaveEvaluator(UserMainInformation, false);
                    SendEmailNewUser(UserMainInformation);
                }
                else
                {
                    id = _UserDAO.SaveEvaluator(UserMainInformation, true);
                }
                dic.Add("Valid", true);
                dic.Add("Id", id);
                UserMainInformation.Id = id;
            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }

            return Json(Utility.GetExtendedJsonResult(dic));


        }
        private void SendEmailNewUser(UserMainInformation model)
        {
            string attachPath = "EmailTemplate/RegistertaionEvaluator.html";
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", attachPath);
            var fileContents = System.IO.File.ReadAllText(path);
            fileContents = EmailSMSHelper.ReplaceTemplateFields(model, fileContents);
            MailRequest request = new MailRequest();
            request.Subject = " مبادرة اعتماد الخبراء  في مجال التواصل والعلاقات العامة";
            request.Body = fileContents;
            request.ToEmail = model.Email;
            _mailService.SendEmailAsync(request);
        }


        public IActionResult AddEvaluator(string Id = "")
        {
            UserMainInformation model = new UserMainInformation();
            if (!string.IsNullOrEmpty(Id))
            {
                model = _UserDAO.GetByGuid(Id);
            }

            return View(model);
        }
        public IActionResult Index()
        {
            return new RedirectResult("~/Evaluation/ApplicationList");
           // return View();
        }
        public IActionResult List()
        {
            UserMainInformation obj = UserInfo;
            if (obj == null || obj.Id <= 0)
            {
                return new RedirectResult("~/account/Login");
            }
            List<ApplicationFormUI> lst = _evaluationDAO.GetAll();
            return View(lst);
        }
        public IActionResult ApplicationList(ApplicationFormFilter model)
        {
            UserMainInformation obj = UserInfo;
            if (obj == null || obj.Id <= 0)
            {
                return new RedirectResult("~/account/Login");
            }
            model.EvaluatorGroupId = obj.EvaluatorGroupId;
            List<ApplicationFormUI> lst = _ApplicationFormDAO.GetEvaluationApplicationForms(model,obj);
            return View(lst);
        }
        public ActionResult GetEvaluationDegree(ApplicationEvaluation obj)
        {
            var dic = new Dictionary<string, object>();
            try
            {

                obj.ApplicationUserGUID = UserInfo.GUID;
                var result = _evaluationDAO.GetEvaluationDegree(obj);
                dic.Add("result", result);
                dic.Add("Valid", true);
            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }

            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult SaveEvaluationDegree(ApplicationEvaluation obj)
        {
            var dic = new Dictionary<string, object>();
            try
            {

                int id = 0;
                obj.ApplicationUserGUID = UserInfo.GUID;
                _evaluationDAO.SaveEvaluationDegree(obj);

                dic.Add("Valid", true);
                dic.Add("Id", id);
            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }

            return Json(Utility.GetExtendedJsonResult(dic));


        }
        public ActionResult FinishEvaluationDegree(ApplicationEvaluation obj)
        {
            var dic = new Dictionary<string, object>();
            try
            {

                int id = 0;
                obj.ApplicationUserGUID = UserInfo.GUID;
               var result =  _evaluationDAO.FinishEvaluationDegree(obj);

                dic.Add("Valid", result);
                dic.Add("Id", id);
            }
            catch (Exception ex)
            {

                dic.Add("Valid", false);
                dic.Add("ServiceError", ex.Message);
            }

            return Json(Utility.GetExtendedJsonResult(dic));


        }
    }
}

ExpertSolution/Views/Evaluation/AddEvaluator.cshtml
@model UserMainInformation;

@{
    ViewData["Title"] = "إضافة مٌقيم";

}
@inject ICommonDAO _CommonDAO;
@{
    var countyLst = _CommonDAO.GetCountry();
    var EvaluatorGroupLst = _CommonDAO.GetEvaluatorGroup();
}
<section class="section dashboard" style="font-size:larger;">
<div class="card mb-3" style="font-size:larger;">
    <div class="card-body">
        <div class=" pb-2">
            <h5 class="card-title text-center pb-0 fs-4">بيانات المٌقيم</h5>
        </div>
        <input type="hidden" id="hiddenUserGUID" value="@Model.GUID" />
        <form class="row g-1 needs-validation" novalidate onsubmit="return false;" >
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">الاسم </label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="txtFirstName" required value="@Model.ContactFullName">
                    <div class="invalid-feedback"> يجب إدخال الاسم </div>
                </div>
              @*  <label for="inputText" class="col-sm-2 col-form-label">الاسم الأخير</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="txtLastName" required>
                    <div class="invalid-feedback">يجب إدخال الاسم الأخير</div>
                </div>*@
            </div>
            <div class="row mb-3">
                <label for="inputText" class="col-sm-2 col-form-label">الدولة</label>
                <div class="col-sm-4">
                    <select class="form-select" id="selectCountryId" aria-label="Default select example" required>
                        <option selected=""></option>
                        @foreach (var obj in countyLst)
                        {
                            if (obj.Id == Model.CountryId)
                            {
                                <option selected value="@obj.Id">@obj.Name.Trim()</option>
                            }
                            else
                            {
                                <option value="@obj.Id">@obj.Name.Trim()</option>
                            }
                        }
                    </select>

                    <div class="invalid-feedback">يجب اختيار الدولة</div>
                </div>
                  <label class="col-sm-2 col-form-label">رقم الهاتف</label>
                <div class="col-sm-4">
                    <input type="text" name="Phone" class="form-control" id="txtPhone" value="@Model.Phone" required>
                    <div class="invalid-feedback"> يجب إدخال رقم الهاتف</div>
                </div>
            </div>
            <div class="row mb-3">
              
                <label for="inputText" class="col-sm-2 col-form-label">البريد الإلكتروني</label>
                <div class="col-sm-4">
                    <input type="email" name="Email" class="form-control" id="txtEmail" value="@Model.Email" required style="padding-left:8px">
                    <div class="invalid-feedback">يجب إدخال بريد إلكترونى صحيح</div>
                </div>
                <label class="col-sm-2 col-form-label">كلمة المرور </label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" id="txtPassword" dir="ltr" name="txtPassword" value="@Model.Password" minlength="6" required style="padding-left:8px">
                    <div class="invalid-feedback">يجب إدخال كلمة المرور على الاقل 6 حروف</div>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputText" class="col-sm-2 col-form-label">المجموعة</label>
                <div class="col-sm-4">
                    <select class="form-select" id="selectEvaluatorGroupId" aria-label="Default select example">
                        <option selected=""></option>
                        @foreach (var obj in EvaluatorGroupLst)
                        {
                            if (obj.Id == Model.EvaluatorGroupId)
                            {
                                <option selected value="@obj.Id">@obj.Name.Trim()</option>
                            }
                            else
                            {
                                <option value="@obj.Id">@obj.Name.Trim()</option>
                            }
                        }
                    </select>

                </div>
                
            </div>

        
            <div style="text-align:center" >
                <button class="btn btn-primary " onclick="Expert.Evaluation.Save();" id="submitBtn">حفظ</button>
            </div>
           
        </form>

    </div>
</div>
</section>
<script src="~/js/Expert.Evaluation.js"></script>

ExpertSolution/Views/Evaluation/ApplicationList.cshtml
@model List<ApplicationFormUI>;
@inject IEvaluationDAO _EvaluationDAO;
@{
    var userInfo = Html.GetUserinfo();
    ViewData["Title"] = "استمارات المشاركين";
}
<link href="~/assets/dataTables/dataTables.bootstrap4.css" rel="stylesheet">
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body mt-3">
                <div class="table-responsive">
                    <table id="file_export" class="table table-striped table-bordered display">
                        <thead>
                            <tr>
                                <th>اسم المؤسسة/الجمعية</th>
                                <th>الدولة</th>
                                <th>المدينة/المحافظة</th>
                                <th>حجم المؤسسة</th>
                                <th>تاريخ التأسيس</th>
                                <th>رقم الهاتف الرئيسي</th>
                                <th> البريد الإلكتروني</th>
                                <th>مسؤول الاتصال</th>
                                <th>حالة التقييم</th>
                                <th>المجموع</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <a href="/ApplicationForm?id=@item.GUID" target="_blank">
                                            @item.JobTitle
                                        </a>
                                    </td>
                                    <td>@item.CountryName</td>
                                @*     <td>@item.City</td>
                                    <td>
                                        @if (item.OrganizationSize == 1)
                                        {
                                            <span class="badge border-primary border-1 text-primary">مؤسسة كبيرة</span>
                                        }
                                        else if (@item.OrganizationSize == 3)
                                        {
                                            <span class="badge border-primary border-1 text-secondary">مؤسسة صغيرة</span>
                                        }
                                        else
                                        {
                                            <span class="badge border-primary border-1 text-info">مؤسسة متوسطة</span>
                                        }


                                    </td> *@
                                    <td>@item.BirthDate</td>
                                    <td>@item.Phone</td>
                                    <td>@item.Email</td>
                                    <td>@item.ContactFullName</td>
                                    <td>
                                        @if (item.EvalautionStatus == "NotStarted")
                                        {
                                            <span class="badge bg-danger">لم تبدأ </span>
                                        }
                                        else if (@item.EvalautionStatus == "InProgress")
                                        {
                                            <span class="badge bg-warning">قيد التقييم</span>
                                        }
                                        else if (@item.EvalautionStatus == "Finished")
                                        {
                                            <span class="badge bg-success">تم التقييم</span>
                                        }
                                      
                                        else
                                        {
                                            @item.ApplicationFormStatus
                                        }
                                    </td>
                                    <td>
                                        @{
                                            var result = _EvaluationDAO.GetEvaluationSummery(userInfo.GUID, item.GUID);
                                           
                                            if (result != null && result.Degree > 0)
                                            {
                                                @result.Degree
                                            }
                                        }
                                        </td>
                                </tr>
                            }

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/assets/datatables/datatables.min.js"></script>
<script src="~/assets/datatables/dataTables.buttons.min.js"></script>
<script src="~/assets/datatables/buttons.flash.min.js"></script>
<script src="~/assets/datatables/jszip.min.js"></script>
<script src="~/assets/datatables/pdfmake.min.js"></script>
<script src="~/assets/datatables/vfs_fonts.js"></script>
<script src="~/assets/datatables/buttons.html5.min.js"></script>
<script src="~/assets/datatables/buttons.print.min.js"></script>
<script src="~/assets/datatables/datatable-advanced.init.js"></script>
<script src="~/js/Expert.ApplicationManage.js"></script>

ExpertSolution/Views/Evaluation/Index.cshtml
@{
    ViewData["Title"] = "الصفحة الرئيسية";
}

<section class="section dashboard" style="font-size:larger">
   
</section>

ExpertSolution/Views/Evaluation/List.cshtml
@model List<ApplicationFormUI>;
@{

    ViewData["Title"] = "قائمة المٌقيمين";
}
<link href="~/assets/dataTables/dataTables.bootstrap4.css" rel="stylesheet">
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body mt-3">
                <div class="table-responsive">
                    <table id="file_export" class="table table-striped table-bordered display">
                        <thead>
                            <tr>
                                <th>الإسم</th>
                                <th>الدولة</th>
                                <th>رقم الهاتف </th>
                                <th> البريد الإلكتروني</th>
                                <th> المجموعة</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <a href="@Url.Action("AddEvaluator","Evaluation", new { Id =item.GUID})"> @item.ContactFullName</a>
                                    </td>
                                    <td>@item.CountryName</td>
                                    <td>@item.Phone</td>
                                    <td>@item.Email</td>
                                    <td>@item.GroupName</td>
                                </tr>
                            }

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/assets/datatables/datatables.min.js"></script>
<script src="~/assets/datatables/dataTables.buttons.min.js"></script>
<script src="~/assets/datatables/buttons.flash.min.js"></script>
<script src="~/assets/datatables/jszip.min.js"></script>
<script src="~/assets/datatables/pdfmake.min.js"></script>
<script src="~/assets/datatables/vfs_fonts.js"></script>
<script src="~/assets/datatables/buttons.html5.min.js"></script>
<script src="~/assets/datatables/buttons.print.min.js"></script>
<script src="~/assets/datatables/datatable-advanced.init.js"></script>
<script src="~/js/Expert.ApplicationManage.js"></script>